-- Inscrições de notificações do PWA. A chave privada de envio fica somente
-- na Vercel; esta tabela guarda apenas o endereço público do dispositivo.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  usuario text not null,
  perfil text not null check (perfil in ('Aluna', 'Professora', 'Secretaria', 'Master')),
  endpoint text not null unique,
  subscription jsonb not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notificacoes_enviadas (
  id bigint generated by default as identity primary key,
  chave text not null unique,
  usuario text not null,
  tipo text not null,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
alter table public.notificacoes_enviadas enable row level security;

-- As duas tabelas são usadas exclusivamente pelas funções protegidas da Vercel
-- com service_role. Não há acesso direto do navegador.
