-- Exercícios por método da aula de Prática.
-- O app.py já usa esta tabela; esta migration só cria a estrutura quando ela
-- ainda não existe e, por isso, não altera nenhum exercício já registrado.
create table if not exists public.exercicios_registro (
  id bigint generated by default as identity primary key,
  aluna text not null,
  data text not null,
  instrutora text,
  disciplina text not null default 'Prática',
  material text not null,
  exercicio text not null,
  dificuldades jsonb not null default '[]'::jsonb,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists exercicios_registro_busca_idx
  on public.exercicios_registro (aluna, data, disciplina, material, ordem);

-- O PWA atual usa as mesmas permissões legadas das outras tabelas do GEM.
-- Quando a migração de autenticação por perfil/RLS estiver concluída, esta
-- política deve ser substituída por regras restritas ao usuário autenticado.
alter table public.exercicios_registro enable row level security;

drop policy if exists "exercicios registro acesso legado pwa" on public.exercicios_registro;
create policy "exercicios registro acesso legado pwa" on public.exercicios_registro
  for all to anon, authenticated
  using (true)
  with check (true);
