-- Professora coordenadora por período.
-- Esta tabela é adicional: não muda nem remove professoras, logins, escalas
-- ou os registros já usados pelo app.py em Streamlit.

create table if not exists public.coordenacoes_professoras (
  id bigint generated by default as identity primary key,
  professora text not null,
  inicio date not null,
  fim date not null,
  periodo text not null default 'Coordenação',
  created_at timestamptz not null default now(),
  constraint coordenacoes_professoras_periodo_valido check (fim >= inicio)
);

create index if not exists coordenacoes_professoras_periodo_idx
  on public.coordenacoes_professoras (inicio, fim);

alter table public.coordenacoes_professoras enable row level security;

-- O GEM ainda possui contas legadas de professora validadas por RPC, sem uma
-- sessão individual do Supabase. Estas políticas mantêm a compatibilidade da
-- interface atual. Quando todas as contas forem migradas para Supabase Auth,
-- devem ser substituídas por políticas baseadas no papel da sessão.
drop policy if exists "coordenacoes leitura pwa legado" on public.coordenacoes_professoras;
create policy "coordenacoes leitura pwa legado"
  on public.coordenacoes_professoras for select to anon, authenticated using (true);

drop policy if exists "coordenacoes escrita pwa legado" on public.coordenacoes_professoras;
create policy "coordenacoes escrita pwa legado"
  on public.coordenacoes_professoras for all to anon, authenticated
  using (true) with check (true);

grant select, insert, update, delete on public.coordenacoes_professoras to anon, authenticated;
grant usage, select on sequence public.coordenacoes_professoras_id_seq to anon, authenticated;
