-- Base pedagógica para uma NOVA unidade GEM.
-- Execute este arquivo na base Supabase exclusiva do novo GEM, antes do
-- primeiro login. Não execute na base principal da plataforma (que contém
-- gems, plataforma_usuarios e gem_secretarias).
--
-- Esta base começa vazia e é compatível com todas as telas do PWA: cadastro,
-- rodízio, chamada, registros, tarefas, provas, mensagens e analíticos.

create extension if not exists pgcrypto;

create table if not exists public.alunas (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  turma text not null default 'Sem turma',
  login text,
  senha text,
  ativo boolean not null default true,
  foto_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.professoras (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  login text,
  senha text,
  ativo boolean not null default true,
  foto_path text,
  created_at timestamptz not null default now()
);

create table if not exists public.secretarias (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.config_metodos (
  id bigint generated by default as identity primary key,
  nome text not null,
  categoria text not null,
  created_at timestamptz not null default now(),
  unique (nome, categoria)
);

create table if not exists public.modelos_logistica (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  vigencia_inicio date not null,
  vigencia_fim date,
  status text not null default 'rascunho',
  configuracao jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.calendario (
  id text primary key,
  escala jsonb not null default '[]'::jsonb,
  modelo_logistica_id uuid references public.modelos_logistica(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.historico_geral (
  id bigint generated by default as identity primary key,
  "Data" text not null,
  "Aluna" text not null,
  "Tipo" text,
  "Status" text,
  "Observacao" text,
  "Licao_Atual" text,
  "Licao_Casa" text,
  "Dificuldades" jsonb not null default '[]'::jsonb,
  "Instrutora" text,
  "Secretaria" text,
  created_at timestamptz not null default now()
);
create index if not exists historico_geral_busca_idx on public.historico_geral ("Aluna", "Data", "Tipo");

create table if not exists public.exercicios_registro (
  id bigint generated by default as identity primary key,
  aluna text not null,
  data text not null,
  instrutora text,
  disciplina text not null default 'Prática',
  material text not null,
  exercicio text not null,
  dificuldades jsonb not null default '[]'::jsonb,
  ordem integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.folgas_professoras (
  data text primary key,
  coordenadora text,
  professoras jsonb not null default '[]'::jsonb,
  observacao text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.professoras_fixas (
  aluna text primary key,
  professora text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.coordenacoes_professoras (
  id bigint generated by default as identity primary key,
  professora text not null,
  inicio date not null,
  fim date not null,
  periodo text not null default 'Coordenação',
  created_at timestamptz not null default now(),
  check (fim >= inicio)
);

create table if not exists public.estudo_diario (
  id bigint generated by default as identity primary key,
  aluna text not null,
  data text not null,
  horarios jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  unique (aluna, data)
);

create table if not exists public.licoes_feitas_alunas (
  id bigint generated by default as identity primary key,
  aluna text not null,
  historico_id text not null,
  created_at timestamptz not null default now(),
  unique (aluna, historico_id)
);

create table if not exists public.objetivos_pedagogicos (
  aluna text primary key,
  texto text not null default '',
  professora text,
  updated_at timestamptz not null default now()
);

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  titulo text not null,
  data_avaliacao date not null,
  created_at timestamptz not null default now()
);

create table if not exists public.avaliacao_notas (
  id bigint generated by default as identity primary key,
  avaliacao_id bigint not null references public.avaliacoes(id) on delete cascade,
  aluna text not null,
  disciplina text not null,
  nota numeric not null,
  professora text,
  created_at timestamptz not null default now(),
  unique (avaliacao_id, aluna, disciplina)
);

create table if not exists public.avaliacao_responsaveis (
  avaliacao_id bigint not null references public.avaliacoes(id) on delete cascade,
  aluna text not null,
  disciplina text not null,
  professora text not null,
  created_at timestamptz not null default now(),
  primary key (avaliacao_id, aluna, disciplina)
);

create table if not exists public.mensagens (
  id bigint generated by default as identity primary key,
  de text not null,
  para text not null,
  texto text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.gabaritos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  disciplina text,
  turma text,
  aluna text,
  observacao text not null default '',
  professora text,
  arquivo_path text not null,
  arquivo_nome text,
  data_correcao date,
  visivel_alunas boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.config_visual_gem (
  id integer primary key check (id = 1),
  logo_path text,
  updated_at timestamptz not null default now()
);
insert into public.config_visual_gem (id) values (1) on conflict (id) do nothing;

create table if not exists public.secretaria_perfil (
  id integer primary key check (id = 1),
  nome_exibicao text not null default 'Coordenação',
  foto_path text,
  updated_at timestamptz not null default now()
);
insert into public.secretaria_perfil (id) values (1) on conflict (id) do nothing;

-- O PWA atual usa autenticação legada por login e senha nas tabelas de
-- professoras/alunas. As políticas abaixo mantêm compatibilidade enquanto a
-- unidade ainda não usa Supabase Auth por perfil.
do $$
declare
  tabela text;
begin
  foreach tabela in array array[
    'alunas', 'professoras', 'secretarias', 'config_metodos', 'modelos_logistica',
    'calendario', 'historico_geral', 'exercicios_registro', 'folgas_professoras',
    'professoras_fixas', 'coordenacoes_professoras', 'estudo_diario',
    'licoes_feitas_alunas', 'objetivos_pedagogicos', 'avaliacoes', 'avaliacao_notas',
    'avaliacao_responsaveis', 'mensagens', 'gabaritos', 'config_visual_gem',
    'secretaria_perfil'
  ] loop
    execute format('alter table public.%I enable row level security', tabela);
    execute format('drop policy if exists "pwa acesso legado" on public.%I', tabela);
    execute format('create policy "pwa acesso legado" on public.%I for all to anon, authenticated using (true) with check (true)', tabela);
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', tabela);
  end loop;
end $$;

grant usage, select on all sequences in schema public to anon, authenticated;

-- Buckets usados pelos documentos e pelos fallbacks de imagem das unidades.
insert into storage.buckets (id, name, public)
values ('gabaritos', 'gabaritos', false), ('logo_gem', 'logo_gem', false),
       ('fotos_alunas', 'fotos_alunas', false), ('fotos_professoras', 'fotos_professoras', false),
       ('fotos_secretaria_gem', 'fotos_secretaria_gem', false)
on conflict (id) do nothing;

drop policy if exists "pwa arquivos do gem" on storage.objects;
create policy "pwa arquivos do gem" on storage.objects
  for all to anon, authenticated
  using (bucket_id in ('gabaritos', 'logo_gem', 'fotos_alunas', 'fotos_professoras', 'fotos_secretaria_gem'))
  with check (bucket_id in ('gabaritos', 'logo_gem', 'fotos_alunas', 'fotos_professoras', 'fotos_secretaria_gem'));

-- Execute depois a migration 001_validar_login_professoras_alunas.sql nesta
-- mesma base para ativar o login de professoras e alunas.
